// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbyypycatfitwonhoilb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpieXlweWNhdGZpdHdvbmhvaWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTk1NzUsImV4cCI6MjA2NjQzNTU3NX0.N0GC3eoJAybA6E6jbFDpfixPThIfnzxzFbb_v8hvXVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);